name: CI

on:
  push:
    branches: ["master", "main"]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          components: rustfmt, clippy

      - name: Install cargo-next
        uses: taiki-e/install-action@ace6ebe54a6a0c86dfb5f7764b17f793b6925bc3 # v2.82.3
        with:
          tool: nextest

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy (strict)
        run: >
          cargo clippy --all-targets

      - name: Tests
        run: cargo nextest run

