name: CI

on:
  push:
    branches: ["master", "main"]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
        with:
          components: rustfmt, clippy

      - name: Install cargo-next
        uses: taiki-e/install-action@7623a79cdfecb99d681017af368ca353d9f49bb5 # v2.87.19
        with:
          tool: nextest

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy (strict)
        run: >
          cargo clippy --all-targets

      - name: Tests
        run: cargo nextest run

